# Generated by Django 6.0.2 on 2026-02-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom de la médiathèque",
                        max_length=200,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Adresse email de contact de la médiathèque",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de téléphone de la médiathèque",
                        max_length=20,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Adresse complète de la médiathèque",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactivez cette case pour désactiver la médiathèque",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Médiathèque",
                "verbose_name_plural": "Médiathèques",
                "ordering": ["-created_at"],
            },
        ),
    ]
