# Generated by Django 6.0.2 on 2026-02-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Désactivez cette case pour désactiver la médiathèque",
                verbose_name="Active",
            ),
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="libraries_l_is_acti_8b369a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(
                fields=["city", "is_active"], name="libraries_l_city_edd64e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(fields=["name"], name="libraries_l_name_d9a53a_idx"),
        ),
    ]
