# Generated by Django 6.0.2 on 2026-02-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("libraries", "0002_alter_library_created_at_alter_library_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Date d'inscription"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Désactivez cette case pour désactiver le compte",
                verbose_name="Actif",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrateur"),
                    ("library_admin", "Administrateur de médiathèque"),
                    ("reader", "Lecteur"),
                ],
                db_index=True,
                default="reader",
                help_text="Le rôle détermine les permissions de l'utilisateur",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["role", "library"], name="accounts_cu_role_4cf19a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["is_active", "date_joined"],
                name="accounts_cu_is_acti_243c63_idx",
            ),
        ),
    ]
