# Generated by Django 6.0.2 on 2026-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="MediaBibli",
                        help_text="Nom affiché dans le logo et le titre du site",
                        max_length=100,
                        verbose_name="Nom du site",
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True,
                        help_text="Description du site affichée dans les métadonnées",
                        verbose_name="Description",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Adresse email de contact affichée publiquement",
                        max_length=254,
                        verbose_name="Email de contact",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone de contact"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="config/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="config/favicons/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#2563eb",
                        help_text="Code couleur hexadécimal (ex: #2563eb)",
                        max_length=7,
                        verbose_name="Couleur principale",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Activez pour afficher une page de maintenance",
                        verbose_name="Mode maintenance",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du site",
                "verbose_name_plural": "Configuration du site",
            },
        ),
    ]
